package goaxis

import (
    "fmt"
)

type hub struct {
    module string
    notify func(mode string, caller ICaller, ds IDataSet) error
}

func newHub(module string, notify func(mode string, caller ICaller, ds IDataSet) error) IHub {
    return &hub{module: module, notify: notify}
}

func (p *hub) Caller(names ...string) ICaller {
    return newCaller(p.module).Push(names...)
}

// request by sync, example: module A get data from module B
func (p *hub) SyncPull(caller ICaller, ds IDataSet) error {
    if ds == nil {
        return fmt.Errorf("SyncPull failed with invalid param, ds: %+v", ds)
    }
    return p.notify(C_Mode_Pull, caller, ds)
}

// request by async, example: websocket module A wait data to send from a channel generated by module B
func (p *hub) ASyncPull(caller ICaller, ds IDataSet) error {
    if ds == nil {
        return fmt.Errorf("ASyncPull failed with invalid param, ds: %+v", ds)
    }

    // use the customize getHook
    if ds.(*dataSet).getHook != nil {
        go p.notify(C_Mode_Pull, caller, ds)
        return nil
    }

    waitSetCh := make(chan byte, 1)
    var ptrWaitSetCh *chan byte = &waitSetCh
    if pds, ok := ds.(*dataSet); ok && pds != nil {
        pds.ResetHookForGet(func(v IValue) error {
            if ptrWaitSetCh != nil && *ptrWaitSetCh != nil {
                <- *ptrWaitSetCh
                close(*ptrWaitSetCh)
                *ptrWaitSetCh = nil
            }
            return nil
        })
    }

    go func() {
        if p.notify(C_Mode_Pull, caller, ds) != nil {
            return
        }
        if ptrWaitSetCh != nil && *ptrWaitSetCh != nil {
            *ptrWaitSetCh <- byte(0)
        }
    }()
    return nil
}

// broadcast data to others module, example: websocket module A broadcast data once receive something from network
func (p *hub) SyncPush(caller ICaller, ds IDataSet) error {
    return p.notify(C_Mode_Push, caller, ds)
}

// broadcast data to others module, example: websocket module A broadcast data once receive something from network
func (p *hub) ASyncPush(caller ICaller, ds IDataSet) error {
    go p.notify(C_Mode_Push, caller, ds)
    return nil
}


